### ISSUE TITLE
Research on Qr code

### ISSUE THREAD

**Issue by Edema-wxd** [zuri-training/QR_GEN_TEAM-53#13]
Research detailing what's in trend with QR codes right now, what they are failing at and how we can improve on it

https://qr.io/?clid=Cj0KCQjw8uOWBhDXARIsAOxKJ2FymmXdhBnxCJbfXLxjrPDNFBcyUwSBNNOe2A8kJN4l6FmY70C-39YaAv5VEALw_wcB

**Comment by joeblinx39** [comment]
[QR code  Research.pdf](https://github.com/zuri-training/QR_GEN_TEAM-53/files/9193244/QR.code.Research.pdf)
