### ISSUE TITLE
Front end ( signing in )

### ISSUE THREAD

**Issue by Edema-wxd** [zuri-training/QR_GEN_TEAM-53#27]
code up these pages, from the FIgma board, the color scheme hasn't been applied yet but use the colors on ground

you should use a grid layout as it has less code and is easier to convert to mobile view

create a templates folder and build the sites, when done push back there on a separate branch

figma link: https://www.figma.com/file/DaCupcCqB7ZJ3ixvHBsTyi/Proj-QR-Main-board?node-id=29%3A3

link to download able image: https://drive.google.com/drive/folders/1cmDaot5kfkMNq6zNaVGlYNwNbad6OmAn?usp=sharing

push / upload here: https://github.com/zuri-training/QR_GEN_TEAM-53/tree/testing/qrgen53/accounts

- [x] sign in page
- [x] sign up  page
- [x] forgot password page
- [x] recovery page 
- [x] New password

**Comment by Edema-wxd** [comment]
@Ralatcode are you done

**Comment by Ralatcode** [comment]
Almost done, just adding some finishing touches.

**Comment by Edema-wxd** [comment]
@Ralatcode, i moved @Gadera to start coding up the landing page mobile view
so no vex, the five pages are yours, 

the pages have been completed on the HiFi side of the Figma Board

please use a single CSS file and use css variables to make it easier to change color scheme when designers are done

link to resources: https://www.youtube.com/watch?v=oZPR_78wCnY

**Comment by Ralatcode** [comment]
Noted
