### ISSUE TITLE
Documentation redesign

### ISSUE THREAD

**Issue by Edema-wxd** [zuri-training/QR_GEN_TEAM-53#57]
We need to improve on our Documentation and what better way than reading and examining other projects files.

Provided below is a list of the teams from the first presentation, your goal is to read understand and interact with their file, once that is done, compile everything into a single document for us to use on our own Documentation file

- [x] [Team 24](https://bit.ly/Team24_PriceCompare_BE_Doc) @LEWAMI 
- [x] [Team 23](https://docs.google.com/document/d/1LwY4xf3l5XciiLNhw41vyeaFBxyWQHW0W8_FRE-xsR4/edit)

 @LEWAMI  i need you to compile the documents and get it to me ASAP

**Comment by LEWAMI** [comment]
Alright
