### ISSUE TITLE
Final Presentation creation

### ISSUE THREAD

**Issue by Edema-wxd** [zuri-training/QR_GEN_TEAM-53#58]
Our first presentation wasn't what we expected because it was rushed so it turned out as it did.
To prevent that from happening again, you guys would form a team and create a new presentation, 

here is a list of deliverables required.
@Fif1chan  is team lead

- [ ] Updated readme doc @Ayomidey-tech 
- [ ] Updated Documentation @LEWAMI 
- [ ] New Presentation Video @ everyone
- [ ] Script for video Presentation @felicoco4215 , @abygirl001 ( please review the videos below)
- [ ] review and possible editing of files in Team 53 folder

**Deadline is Thursday**

Here is a compiled file containing the do's and Dont's of the presentation @Fif1chan , @abygirl001 , @felicoco4215 

 [Do's and Dont's](https://docs.google.com/document/d/1TwJgNJsZb5h9x3Zn-q_Dj4KfXCkDHiAnxR8E8gFiqzc/edit?usp=sharing)

here is a link to the files we used in creating the first presentation:

[Team 53 folder](https://drive.google.com/drive/folders/1Kwv8ZzsyFmQtr-j_s9FXtPHdfXbF_IQa?usp=sharing)

Here is a link to other video presentations submitted, watch them and use as inspiration on how we can create our video 

- [Team 22](https://drive.google.com/file/d/1WN4fY-6yUtcSY0eQCqglVKAw_zGubPLV/view?usp=sharing)
- [Team 24](https://drive.google.com/file/d/1RJn5t1aGPuAop-VbFHNF-bvbN8DkadRl/view?usp=sharing)
- [Team 26](https://drive.google.com/file/d/1pewp0L3M3oN4QJRLDn0bzZDmSakOCFyF/view?usp=sharing)
- [Team 64](https://drive.google.com/file/d/1hmEE21JKWkpZefLnzUVwRLpSWKgHpacq/view?usp=sharing)
- [Team 97](https://drive.google.com/file/d/1SDM-RBFSqZrqG7vSGgMHGndkpbndhxp-/view?usp=sharing)

**Comment by LEWAMI** [comment]
Alright

**Comment by abygirl001** [comment]
> 

Alright
