### ISSUE TITLE
Redesign of Readme md

### ISSUE THREAD

**Issue by Edema-wxd** [zuri-training/QR_GEN_TEAM-53#60]
We need to improve on our Readme.md file and what better way than reading and examining other projects Readme.md files.

Provided below is a list of the top 5 teams from the first presentation, your goal is to read understand and interact with their file, once that is done, compile everything into a single document for us to use on our own Readme

- [ ] [Team 22](https://github.com/zuri-training/Price-Compare-Team-22#readme) @Ayomidey-tech 
- [ ] [Team 24](https://github.com/zuri-training/WF-PriceCompare-24/blob/main/README.md)  @abygirl001 
- [ ] [Team 26](https://github.com/zuri-training/Team_26_Repo-Proj_Price_Compare/blob/master/README.md) @abygirl001 
- [ ] [Team 64](https://github.com/zuri-training/Team-64_Favicon-Gen/blob/main/README.md) @felicoco4215 
- [ ] [Team 7](https://github.com/zuri-training/auth-wiki-team7/blob/main/README.md) @felicoco4215 

@Ayomidey-tech  i need you to compile the documents and get it to me ASAP

**Comment by felicoco4215** [comment]
okay noted
